# -*- coding: utf-8 -*-
"""movie_recommendor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpRW1umehr45ppwCr7SWb93cE2RMqEUZ
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir('/content/drive/MyDrive/SKILLIT Courses/AI Level 2/Clustering/Movie_recommendation')
df = pd.read_csv("movie_dataset.csv")
print(df.columns)
def get_title_from_index(index):
	return df[df.index == index]["title"].values[0]
def get_index_from_title(title):
	return df[df.title == title]["index"].values[0]
features = ["keywords","cast","genres","director"]
for feature in features:
  df[feature] = df[feature].fillna('')

def combine_features(row):
  try:
    text=row['keywords'] + ' ' + row['cast'] + ' ' + row['genres'] + ' ' + row['director']
    return text

  except:
    print("Error: ",row['index'])

df["combined_features"] = df.apply(combine_features,axis=1)
df['combined_features']

cv = CountVectorizer()
cm = cv.fit_transform(df["combined_features"])

cos_sim = cosine_similarity(cm)

def movie_finder():
  movie_liked=input("Which is your favorite movie?")
  movie_index=get_index_from_title(movie_liked)
  similar_movies = list(enumerate(cos_sim[movie_index]))
  sorted_similar_movies = sorted(similar_movies,key = lambda x:x[1],reverse=True)
  i=0
  print("You may also like these movies: ")
  for movies in sorted_similar_movies:
    print(get_title_from_index(movies[0]))
    i=i+1
    if i>5:
      break
movie_finder()